---
title: "about"
author: "Gemy Pham & Amy Butts"
date: "10/18/2016"
output: html_document
---
Uber Pick-UP in NYC Shiny App 
==================================
Authors: 
  - Gemy Ngoc Pham
  - Amy Sigrid Butts 


Yellow cabs are easy to spot in the New York City traffic, but Uber drivers are more hidden. This Shiny App aims to explore the Uber Kaggle dataset from  the NYC Taxi & Limousine Commission (TLC)  to explore Uber activities in different boroughs of NYC. 

Kaggle dataset includes  over 4.5 million Uber pickups in New York City from April to September 2014, and 14.3 million more Uber pickups from January to June 2015. 

The dataset contains, roughly, four groups of files:

- Uber trip data from 2014 (April - September), separated by month, with detailed location information
- Uber trip data from 2015 (January - June), with less fine-grained location information
- Non-Uber FHV (For-Hire Vehicle) trips. The trip information varies by company, but can include day of trip, time of trip, pickup location, driver's for-hire license number, and vehicle's for-hire license number.
- Aggregate ride and vehicle statistics for all FHV companies (and, occasionally, for taxi companies)

For the Uber trip data from 2014, there are six files of raw data on Uber pickups in New York City from April to September 2014. The files are separated by month and each has the following columns:
- Date/Time: The date and time of the Uber pickup
- Lat: The latitude of the Uber pickup
- Lon: The longitude of the Uber pickup
- Base: The TLC base company code affiliated with the Uber pickup

This Shiny app explores the Uber trip data from 2014 (April - September)
We want to investigate: 
How has Uber changed the dynamics of NYC for-hire-vehicle service?

The dataset is named "Uber Pickups in New York City" and it is available here: https://www.kaggle.com/fivethirtyeight/uber-pickups-in-new-york-city. 

Take a look for yourself at this Shiny App. 

The data speaks for itself. 


